= Exercises for Intermediate
Carsten Brueggenolte <mail@cbrueggenolte.de>
v1.0.0, March 2021
// Meta Data
:description: Rewritten from the 100+ Python challenging programming exercises"
:keywords: Golang, programming, exercises, challenges
:toc: right
// Settings
:icons: font
:source-highlighter: highlightjs
:sectnums:
:url-project: https://github.com/cblte/100-golang-exercises/
:url-issues: {url-project}/issues


This document contains all the intermediate exercises. If you find an error or a bug or something that could be written better, please get in contact with me. Thanks.

== Exercise 006 : Write a program that calculates and prints the value according to the given formula:

Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 * C * D)/H]

Following are the fixed values of C and H:

- C is 50. H is 30.
- D is the variable whose values should be input to your program in a comma-separated sequence.

Example:

Let us assume the following comma separated input sequence is given to the program: 100,150,180

The output of the program should be: 18,22,24

=== Hints:

- use `math.Sqrt` for the square root
- use `math.Round` for rounding a float operation

== Solution:

link:006/exercise006.go[]


== Exercise 007: Write a program which takes 2 digits and generate a 2 dimensional slice

Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.
Note: i=0,1.., X-1; j=0,1,¡­Y-1.

Example

Suppose the following inputs are given to the program: 3,5

Then, the output of the program should be:
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

=== Hints:
Note: In case of input data being supplied to the question, it should be assumed to be a console input in a comma-separated form.

=== Solution:

link:007/exercise007.go[]

== Exercise 008:


